# Generated by ./update.sh - do not update manually!
# Last updated: 2024-06-10
{
  version = "3.2.9";
  urlhash = "240606";
  arm64_hash = "sha256-wZyaIkJdGDvIw8PrRlOiKpo3rdeELlxYBPyS6llbL4w=";
  amd64_hash = "sha256-DcQWwep4p4aWUAoBNQ9Ge1QBiCxk6BhcziTDSHmRpgY=";
}
