#! /usr/bin/env nix-shell
#! nix-shell -i bash --pure --keep GITHUB_TOKEN -p nix git curl cacert nix-prefetch-git jq
echo "Running script in $(pwd)"
set -euo pipefail

cd $(readlink -e $(dirname "${BASH_SOURCE[0]}"))
echo "start download qq sources"
payload=$(curl https://im.qq.com/rainbow/linuxQQDownload | grep -oP "var params= \K\{.*\}(?=;)")
echo $payload
amd64_url=$(jq -r .x64DownloadUrl.deb <<< "$payload")
arm64_url=$(jq -r .armDownloadUrl.deb <<< "$payload")
if [[ $amd64_url =~ Linux/QQ_(.*?)_([0-9]+)_ ]]; then
  version=${BASH_REMATCH[1]}
  urlhash=${BASH_REMATCH[2]}
fi
amd64_hash=$(nix-prefetch-url $amd64_url)
arm64_hash=$(nix-prefetch-url $arm64_url)

# use friendlier hashes
amd64_hash=$(nix hash to-sri --type sha256 "$amd64_hash")
arm64_hash=$(nix hash to-sri --type sha256 "$arm64_hash")

echo "start copy file"
cat >sources.nix <<EOF
# Generated by ./update.sh - do not update manually!
# Last updated: $(date +%F)
{
  version = "$version";
  urlhash = "$urlhash";
  arm64_hash = "$arm64_hash";
  amd64_hash = "$amd64_hash";
}
EOF